# Generated by Django 3.1.5 on 2021-01-26 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_parser', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlemodel',
            name='time',
            field=models.DateTimeField(auto_now=True, verbose_name='время появления в БД'),
        ),
        migrations.AlterField(
            model_name='articlemodel',
            name='title',
            field=models.CharField(max_length=255, unique=True, verbose_name='название'),
        ),
        migrations.AlterField(
            model_name='articlemodel',
            name='url',
            field=models.CharField(max_length=255, verbose_name='ссылка'),
        ),
    ]
