# Generated by Django 3.1.5 on 2021-01-26 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_parser', '0002_auto_20210126_1054'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ArticleModel',
            new_name='Article',
        ),
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-id'], 'verbose_name': 'статья', 'verbose_name_plural': 'статьи'},
        ),
    ]
