# Generated by Django 3.1.5 on 2021-01-27 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_parser', '0004_auto_20210126_1925'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'verbose_name': 'статья', 'verbose_name_plural': 'статьи'},
        ),
    ]
