# Generated by Django 3.1.5 on 2021-01-28 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_parser', '0005_auto_20210127_1840'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'verbose_name': 'статью', 'verbose_name_plural': 'статьи'},
        ),
        migrations.AlterField(
            model_name='article',
            name='created',
            field=models.DateTimeField(auto_now=True, verbose_name='создано'),
        ),
        migrations.AlterField(
            model_name='article',
            name='url',
            field=models.TextField(verbose_name='ссылка'),
        ),
    ]
