# Generated by Django 3.1.5 on 2021-01-28 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_parser', '0006_auto_20210128_1119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='url',
            field=models.CharField(max_length=2000, verbose_name='ссылка'),
        ),
    ]
